import Foundation

/// Generates docker-compose.pipeline.yaml from selected ANIMA modules.
public struct PipelineComposer: Sendable {

    public init() {}

    /// Compose a docker-compose YAML string from selected modules.
    public func compose(
        modules: [ANIMAModuleManifest],
        platform: JetsonPlatform,
        rosDomainID: Int = 0,
        modelCachePath: String = "/opt/anima/models"
    ) -> String {
        var yaml = """
        # Generated by THOR Pipeline Composer
        # Platform: \(platform.displayName)
        # Modules: \(modules.map(\.name).joined(separator: ", "))

        version: "3.9"

        services:

        """

        for module in modules {
            let backend = module.preferredBackend(for: platform)
            let serviceName = module.name.lowercased().replacingOccurrences(of: " ", with: "-")
            let healthTopic = module.healthTopic ?? "/anima/\(serviceName)/health"
            let port = 8034 + modules.firstIndex(where: { $0.name == module.name })!

            yaml += """
              \(serviceName):
                image: \(module.containerImage)
                container_name: anima-\(serviceName)
                restart: unless-stopped
                environment:
                  - ROS_DOMAIN_ID=\(rosDomainID)
                  - ANIMA_BACKEND=\(backend)
                  - ANIMA_MODULE=\(module.name)
                  - ANIMA_VERSION=\(module.version)
                ports:
                  - "\(port):8034"
                volumes:
                  - \(modelCachePath):/models:ro
                  - /tmp/.X11-unix:/tmp/.X11-unix:ro
                healthcheck:
                  test: ["CMD", "curl", "-f", "http://localhost:8034/health"]
                  interval: 10s
                  timeout: 5s
                  retries: 3
                  start_period: 30s
                deploy:
                  resources:
                    reservations:
                      devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
                networks:
                  - anima-net

            """
        }

        yaml += """
        networks:
          anima-net:
            driver: bridge

        """

        return yaml
    }

    /// Validate modules can run together on the given platform.
    public func validateCompatibility(
        modules: [ANIMAModuleManifest],
        platform: JetsonPlatform,
        gpuMemoryMB: Int = 0
    ) -> [PipelineValidationIssue] {
        var issues: [PipelineValidationIssue] = []

        for module in modules {
            if !module.supportsJetson(platform) {
                issues.append(PipelineValidationIssue(
                    module: module.name,
                    severity: .error,
                    message: "\(module.displayName) does not support \(platform.displayName)"
                ))
            }
        }

        // Check total GPU memory if performance profiles provide it
        if gpuMemoryMB > 0 {
            let totalRequired = modules.compactMap { mod in
                mod.performanceProfiles.first(where: { $0.platform.contains("jetson") })?.memoryMb
            }.reduce(0, +)

            if totalRequired > gpuMemoryMB {
                issues.append(PipelineValidationIssue(
                    module: "pipeline",
                    severity: .warning,
                    message: "Total GPU memory required (\(totalRequired) MB) exceeds available (\(gpuMemoryMB) MB)"
                ))
            }
        }

        // Check for duplicate capabilities
        let allCaps = modules.flatMap(\.capabilities).map(\.type)
        let duplicates = Dictionary(grouping: allCaps, by: { $0 }).filter { $0.value.count > 1 }.keys
        for dup in duplicates {
            issues.append(PipelineValidationIssue(
                module: "pipeline",
                severity: .warning,
                message: "Duplicate capability: \(dup) provided by multiple modules"
            ))
        }

        return issues
    }
}

public struct PipelineValidationIssue: Sendable, Identifiable {
    public let id = UUID()
    public let module: String
    public let severity: ValidationSeverity
    public let message: String
}

public enum ValidationSeverity: Sendable {
    case error
    case warning
    case info
}
